apiVersion: v1
kind: ConfigMap
metadata:
  name: gopro-config
  namespace: gopro
  labels:
    app: gopro-app
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "8080"
  HEALTH_LIVE_PATH: "/health/live"
  HEALTH_READY_PATH: "/health/ready"
