apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-go-ingress
  namespace: devops-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: devops-go-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-go-service
            port:
              number: 80
  tls:
  - hosts:
    - devops-go-app.example.com
    secretName: devops-go-tls

