apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-go-sample
  labels:
    app: k8s-go-sample
spec:
  scaleTargetRef:
    apiVersion: autoscaling/v2
    kind: Deployment
    name: k8s-go-sample
    labels:
      app: k8s-go-sample
  minReplicas: 3
  maxReplicas: 5
  minAvailableReplicas: 1
  maxUnavailableReplicas: 1
  scaleTarget:
    cpuUtilizationTarget: 70%
  memoryUtilizationTarget: 512Mi
  stabilizationWindowSeconds: 300
---
