// Topic data structure for the Go Pro curriculum
// 15 advanced Go project topics organized into 5 phases

export interface Exercise {
  id: string;
  title: string;
  description: string;
  requirements: string[];
  difficulty: 'easy' | 'medium' | 'hard';
  starterCode: string;
  solutionHint: string;
  completionMethod: 'code_review' | 'test' | 'manual';
}

export interface Topic {
  id: string;
  title: string;
  description: string;
  duration: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  icon: string;
  color: string;
  projectPath: string;
  phase: number;
  phaseName: string;
  order: number;
  topics: string[];
  learningOutcomes: string[];
  prerequisites: string[];
  exercises: Exercise[];
  githubUrl: string;
}

// Phase metadata for curriculum grouping
export const phaseMetadata = [
  { phase: 1, title: 'Foundation Patterns', icon: 'zap', color: 'text-yellow-500' },
  { phase: 2, title: 'Communication Patterns', icon: 'globe', color: 'text-blue-500' },
  { phase: 3, title: 'Distributed & Cloud', icon: 'trending', color: 'text-purple-500' },
  { phase: 4, title: 'Specialized Domains', icon: 'award', color: 'text-green-500' },
  { phase: 5, title: 'GraphQL & Integration', icon: 'code', color: 'text-orange-500' },
];

// All 15 topics organized by phase
export const topics: Topic[] = [
  // Phase 1: Foundation Patterns (4 topics)
  {
    id: 'rest-api',
    title: 'REST API Design',
    description: 'Build production-ready REST APIs with Go using the standard library and popular frameworks.',
    duration: '4-6 hours',
    difficulty: 'intermediate',
    icon: '🌐',
    color: 'bg-gradient-to-r from-blue-500 to-cyan-500',
    projectPath: 'basic/projects/rest-api',
    phase: 1,
    phaseName: 'Foundation Patterns',
    order: 1,
    topics: ['HTTP Methods', 'Routing', 'Middleware', 'Error Handling', 'Authentication'],
    learningOutcomes: [
      'Design clean RESTful API endpoints',
      'Implement request/response handling with Go',
      'Add authentication and authorization middleware',
      'Handle errors consistently across API',
    ],
    prerequisites: ['Go basics', 'HTTP protocol understanding'],
    exercises: [
      {
        id: 'rest-api-1',
        title: 'Basic CRUD Endpoints',
        description: 'Implement CRUD operations for a resource',
        requirements: ['GET /users returns list', 'POST /users creates user', 'PUT /users/:id updates user', 'DELETE /users/:id deletes user'],
        difficulty: 'easy',
        starterCode: 'basic/projects/rest-api/exercises/01-crud/main.go',
        solutionHint: 'Use net/http and define handler functions for each operation',
        completionMethod: 'test',
      },
      {
        id: 'rest-api-2',
        title: 'Request Validation',
        description: 'Add input validation middleware',
        requirements: ['Validate required fields', 'Return 400 for invalid input', 'Use custom error types'],
        difficulty: 'medium',
        starterCode: 'basic/projects/rest-api/exercises/02-validation/main.go',
        solutionHint: 'Create a validation struct with json tags and validate before processing',
        completionMethod: 'test',
      },
      {
        id: 'rest-api-3',
        title: 'Authentication Middleware',
        description: 'Implement JWT-based authentication',
        requirements: ['Validate JWT tokens', 'Extract user claims', 'Protect routes with middleware'],
        difficulty: 'medium',
        starterCode: 'basic/projects/rest-api/exercises/03-auth/main.go',
        solutionHint: 'Use golang-jwt/jwt v5 for token handling',
        completionMethod: 'test',
      },
      {
        id: 'rest-api-4',
        title: 'Graceful Shutdown',
        description: 'Handle server shutdown gracefully',
        requirements: ['Catch SIGTERM signal', 'Finish in-flight requests', 'Close database connections'],
        difficulty: 'hard',
        starterCode: 'basic/projects/rest-api/exercises/04-shutdown/main.go',
        solutionHint: 'Use context.WithCancel and http.Server.Shutdown()',
        completionMethod: 'manual',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/rest-api',
  },
  {
    id: 'cli-tools',
    title: 'CLI Tools & POSIX',
    description: 'Build robust command-line tools with proper signal handling, configuration, and user experience.',
    duration: '3-5 hours',
    difficulty: 'intermediate',
    icon: '⚡',
    color: 'bg-gradient-to-r from-yellow-500 to-orange-500',
    projectPath: 'basic/projects/cli-tools',
    phase: 1,
    phaseName: 'Foundation Patterns',
    order: 2,
    topics: ['Command parsing', 'Signal handling', 'Configuration management', 'User feedback'],
    learningOutcomes: [
      'Parse command-line arguments with flag packages',
      'Handle Unix signals for graceful termination',
      'Implement configuration file loading',
      'Write user-friendly CLI output',
    ],
    prerequisites: ['Go basics', 'Command-line usage'],
    exercises: [
      {
        id: 'cli-1',
        title: 'Argument Parsing',
        description: 'Build a CLI with subcommands and flags',
        requirements: ['Define subcommands', 'Parse boolean and string flags', 'Show help text'],
        difficulty: 'easy',
        starterCode: 'basic/projects/cli-tools/exercises/01-args/main.go',
        solutionHint: 'Use the flag package for basic parsing, consider urfave/cli for subcommands',
        completionMethod: 'test',
      },
      {
        id: 'cli-2',
        title: 'Signal Handling',
        description: 'Handle SIGINT and SIGTERM gracefully',
        requirements: ['Catch interrupt signal', 'Clean up resources', 'Report shutdown status'],
        difficulty: 'medium',
        starterCode: 'basic/projects/cli-tools/exercises/02-signals/main.go',
        solutionHint: 'Use os/signal Notify() and channel for graceful shutdown',
        completionMethod: 'manual',
      },
      {
        id: 'cli-3',
        title: 'Configuration Files',
        description: 'Load and merge multiple config sources',
        requirements: ['Read JSON/YAML config', 'Support environment variable overrides', 'Merge configurations'],
        difficulty: 'medium',
        starterCode: 'basic/projects/cli-tools/exercises/03-config/main.go',
        solutionHint: 'Load from file first, then apply environment variables as overrides',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/cli-tools',
  },
  {
    id: 'concurrent-patterns',
    title: 'Concurrency Patterns',
    description: 'Master Go concurrency with channels, goroutines, and common patterns for parallel processing.',
    duration: '5-7 hours',
    difficulty: 'advanced',
    icon: '🔄',
    color: 'bg-gradient-to-r from-green-500 to-teal-500',
    projectPath: 'basic/projects/concurrent-patterns',
    phase: 1,
    phaseName: 'Foundation Patterns',
    order: 3,
    topics: ['Goroutines', 'Channels', 'Select statements', 'Worker pools', 'Fan-out/fan-in'],
    learningOutcomes: [
      'Design concurrent programs with goroutines',
      'Use channels for safe communication',
      'Implement worker pool patterns',
      'Handle race conditions and deadlocks',
    ],
    prerequisites: ['Go basics', 'Understanding of parallelism'],
    exercises: [
      {
        id: 'conc-1',
        title: 'Goroutine Basics',
        description: 'Launch and manage multiple goroutines',
        requirements: ['Launch 10 concurrent workers', 'Wait for completion with sync.WaitGroup', 'Collect results'],
        difficulty: 'easy',
        starterCode: 'basic/projects/concurrent-patterns/exercises/01-goroutines/main.go',
        solutionHint: 'Use sync.WaitGroup to coordinate goroutines',
        completionMethod: 'test',
      },
      {
        id: 'conc-2',
        title: 'Channel Pipelines',
        description: 'Build data processing pipelines with channels',
        requirements: ['Create producer-consumer pattern', 'Use multiple pipeline stages', 'Close channels properly'],
        difficulty: 'medium',
        starterCode: 'basic/projects/concurrent-patterns/exercises/02-pipelines/main.go',
        solutionHint: 'Use range to consume from channels, close when done',
        completionMethod: 'test',
      },
      {
        id: 'conc-3',
        title: 'Worker Pool',
        description: 'Implement bounded concurrent processing',
        requirements: ['Limit concurrent workers', 'Distribute work evenly', 'Handle job completion'],
        difficulty: 'medium',
        starterCode: 'basic/projects/concurrent-patterns/exercises/03-workers/main.go',
        solutionHint: 'Use buffered channels as job queues',
        completionMethod: 'test',
      },
      {
        id: 'conc-4',
        title: 'Fan-out/Fan-in',
        description: 'Parallelize CPU-intensive work',
        requirements: ['Split work across workers', 'Merge results from multiple sources', 'Maintain order if needed'],
        difficulty: 'hard',
        starterCode: 'basic/projects/concurrent-patterns/exercises/04-fanout/main.go',
        solutionHint: 'Use multiple channels feeding into one, use select for multiplexing',
        completionMethod: 'manual',
      },
      {
        id: 'conc-5',
        title: 'Mutex & Race Detection',
        description: 'Handle shared state safely',
        requirements: ['Use sync.Mutex for protection', 'Run with -race flag', 'Document atomic sections'],
        difficulty: 'hard',
        starterCode: 'basic/projects/concurrent-patterns/exercises/05-mutex/main.go',
        solutionHint: 'Minimize critical sections, prefer channel-based patterns when possible',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/concurrent-patterns',
  },
  {
    id: 'error-handling',
    title: 'Error Handling Patterns',
    description: 'Implement robust error handling with sentinel errors, wrapped errors, and custom error types.',
    duration: '3-4 hours',
    difficulty: 'intermediate',
    icon: '🛡️',
    color: 'bg-gradient-to-r from-red-500 to-pink-500',
    projectPath: 'basic/projects/error-handling',
    phase: 1,
    phaseName: 'Foundation Patterns',
    order: 4,
    topics: ['Sentinel errors', 'Error wrapping', 'Custom error types', 'Error assertion'],
    learningOutcomes: [
      'Create and use sentinel errors',
      'Wrap errors with context using fmt.Errorf',
      'Define custom error types with additional data',
      'Handle errors idiomatically in Go',
    ],
    prerequisites: ['Go basics'],
    exercises: [
      {
        id: 'err-1',
        title: 'Sentinel Errors',
        description: 'Define and use sentinel errors',
        requirements: ['Create package-level error variables', 'Compare errors with errors.Is()', 'Return specific sentinels'],
        difficulty: 'easy',
        starterCode: 'basic/projects/error-handling/exercises/01-sentinel/main.go',
        solutionHint: 'Define var ErrNotFound = errors.New("not found") and use errors.Is()',
        completionMethod: 'test',
      },
      {
        id: 'err-2',
        title: 'Error Wrapping',
        description: 'Add context to errors through the stack',
        requirements: ['Wrap errors with fmt.Errorf', 'Preserve original error', 'Use errors.Is() and errors.As()'],
        difficulty: 'medium',
        starterCode: 'basic/projects/error-handling/exercises/02-wrapping/main.go',
        solutionHint: 'Use %w verb in fmt.Errorf to wrap errors',
        completionMethod: 'test',
      },
      {
        id: 'err-3',
        title: 'Custom Error Types',
        description: 'Create structured errors with additional context',
        requirements: ['Define custom error struct', 'Implement Error() interface', 'Add validation errors with field info'],
        difficulty: 'medium',
        starterCode: 'basic/projects/error-handling/exercises/03-custom/main.go',
        solutionHint: 'Embed error, add fields, use errors.As() to extract',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/error-handling',
  },

  // Phase 2: Communication Patterns (3 topics)
  {
    id: 'grpc-services',
    title: 'gRPC Services',
    description: 'Build high-performance microservices with gRPC, Protocol Buffers, and streaming.',
    duration: '5-7 hours',
    difficulty: 'advanced',
    icon: '📡',
    color: 'bg-gradient-to-r from-purple-500 to-indigo-500',
    projectPath: 'basic/projects/grpc-services',
    phase: 2,
    phaseName: 'Communication Patterns',
    order: 1,
    topics: ['Protocol Buffers', 'gRPC server/client', 'Streaming', 'Interceptors', 'Metadata'],
    learningOutcomes: [
      'Define .proto files and generate Go code',
      'Implement gRPC server with multiple services',
      'Build gRPC clients with proper error handling',
      'Use unary and streaming RPCs effectively',
    ],
    prerequisites: ['Go basics', 'Microservices understanding', 'Protocol Buffers basics'],
    exercises: [
      {
        id: 'grpc-1',
        title: 'Unary RPC',
        description: 'Implement a simple gRPC service',
        requirements: ['Define protobuf messages', 'Implement server handler', 'Create client that calls the service'],
        difficulty: 'medium',
        starterCode: 'basic/projects/grpc-services/exercises/01-unary/main.go',
        solutionHint: 'Use protoc to generate code, implement service interface',
        completionMethod: 'test',
      },
      {
        id: 'grpc-2',
        title: 'Server Streaming',
        description: 'Implement server-side streaming RPC',
        requirements: ['Define stream endpoint in proto', 'Send multiple responses', 'Handle client disconnection'],
        difficulty: 'medium',
        starterCode: 'basic/projects/grpc-services/exercises/02-server-stream/main.go',
        solutionHint: 'Return stream, send messages with Send() method',
        completionMethod: 'test',
      },
      {
        id: 'grpc-3',
        title: 'Client Streaming',
        description: 'Implement client-side streaming RPC',
        requirements: ['Accept stream of requests', 'Process and return aggregated response', 'Handle partial data'],
        difficulty: 'hard',
        starterCode: 'basic/projects/grpc-services/exercises/03-client-stream/main.go',
        solutionHint: 'Use Recv() in a loop, send final response when client closes stream',
        completionMethod: 'test',
      },
      {
        id: 'grpc-4',
        title: 'Bidirectional Streaming',
        description: 'Implement true bidirectional communication',
        requirements: ['Handle concurrent send/recv', 'Process messages as they arrive', 'Graceful stream close'],
        difficulty: 'hard',
        starterCode: 'basic/projects/grpc-services/exercises/04-bidi-stream/main.go',
        solutionHint: 'Use goroutine for send, main loop for recv, select for both',
        completionMethod: 'manual',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/grpc-services',
  },
  {
    id: 'message-queues',
    title: 'Message Queues & Events',
    description: 'Implement event-driven architecture with message queues, pub/sub, and event handling.',
    duration: '4-6 hours',
    difficulty: 'intermediate',
    icon: '📬',
    color: 'bg-gradient-to-r from-cyan-500 to-blue-500',
    projectPath: 'basic/projects/message-queues',
    phase: 2,
    phaseName: 'Communication Patterns',
    order: 2,
    topics: ['Publish/Subscribe', 'Message brokering', 'Event schemas', 'Dead letter queues'],
    learningOutcomes: [
      'Design event-driven architectures',
      'Implement publisher and subscriber patterns',
      'Handle message acknowledgment and retry',
      'Design event schemas with versioning',
    ],
    prerequisites: ['Go basics', 'Microservices understanding'],
    exercises: [
      {
        id: 'mq-1',
        title: 'Basic Pub/Sub',
        description: 'Implement in-memory pub/sub system',
        requirements: ['Create broker struct', 'Support subscribe/unsubscribe', 'Deliver messages to subscribers'],
        difficulty: 'medium',
        starterCode: 'basic/projects/message-queues/exercises/01-pubsub/main.go',
        solutionHint: 'Use map of topics to slice of channels',
        completionMethod: 'test',
      },
      {
        id: 'mq-2',
        title: 'Message Acknowledgment',
        description: 'Add delivery guarantees to the system',
        requirements: ['Track unacknowledged messages', 'Requeue on timeout', 'Support manual ack/nack'],
        difficulty: 'hard',
        starterCode: 'basic/projects/message-queues/exercises/02-ack/main.go',
        solutionHint: 'Store messages in map until acked, use context.WithTimeout for deadline',
        completionMethod: 'manual',
      },
      {
        id: 'mq-3',
        title: 'Event Schema',
        description: 'Design and validate event structures',
        requirements: ['Define event envelope with type/version', 'Validate events on publish', 'Handle unknown event types gracefully'],
        difficulty: 'medium',
        starterCode: 'basic/projects/message-queues/exercises/03-schema/main.go',
        solutionHint: 'Include Type and Version in envelope, switch on type for handling',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/message-queues',
  },
  {
    id: 'websocket',
    title: 'WebSocket Real-time',
    description: 'Build real-time applications with WebSocket connections, hubs, and message broadcasting.',
    duration: '4-5 hours',
    difficulty: 'intermediate',
    icon: '🔌',
    color: 'bg-gradient-to-r from-emerald-500 to-green-500',
    projectPath: 'basic/projects/websocket',
    phase: 2,
    phaseName: 'Communication Patterns',
    order: 3,
    topics: ['WebSocket protocol', 'Connection hub', 'Message broadcasting', 'Heartbeat/ping-pong'],
    learningOutcomes: [
      'Upgrade HTTP connections to WebSocket',
      'Implement connection hub for managing clients',
      'Broadcast messages to connected clients',
      'Handle connection lifecycle and cleanup',
    ],
    prerequisites: ['Go basics', 'HTTP handling'],
    exercises: [
      {
        id: 'ws-1',
        title: 'Basic WebSocket Server',
        description: 'Implement WebSocket upgrade and echo server',
        requirements: ['Upgrade HTTP to WebSocket', 'Read/write messages', 'Handle disconnect gracefully'],
        difficulty: 'easy',
        starterCode: 'basic/projects/websocket/exercises/01-basic/main.go',
        solutionHint: 'Use gorilla/websocket or nhooyr/websocket library',
        completionMethod: 'test',
      },
      {
        id: 'ws-2',
        title: 'Connection Hub',
        description: 'Manage multiple WebSocket connections',
        requirements: ['Register/unregister connections', 'Track connection count', 'Broadcast to all clients'],
        difficulty: 'medium',
        starterCode: 'basic/projects/websocket/exercises/02-hub/main.go',
        solutionHint: 'Use mutex for thread-safe hub, broadcast via channels',
        completionMethod: 'test',
      },
      {
        id: 'ws-3',
        title: 'Heartbeat Mechanism',
        description: 'Keep connections alive with ping/pong',
        requirements: ['Send periodic pings', 'Detect stale connections', 'Close dead connections'],
        difficulty: 'medium',
        starterCode: 'basic/projects/websocket/exercises/03-heartbeat/main.go',
        solutionHint: 'Use SetReadDeadline and ping/pong handlers',
        completionMethod: 'test',
      },
      {
        id: 'ws-4',
        title: 'Typed Message Routing',
        description: 'Route messages based on type',
        requirements: ['Define message envelope with type', 'Route to appropriate handler', 'Handle unknown message types'],
        difficulty: 'hard',
        starterCode: 'basic/projects/websocket/exercises/04-routing/main.go',
        solutionHint: 'Use map of type to handler functions, switch statement for routing',
        completionMethod: 'manual',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/websocket',
  },

  // Phase 3: Distributed & Cloud (3 topics)
  {
    id: 'microservices',
    title: 'Microservices Architecture',
    description: 'Design and build microservices with service discovery, API gateway, and distributed tracing.',
    duration: '6-8 hours',
    difficulty: 'advanced',
    icon: '🏗️',
    color: 'bg-gradient-to-r from-violet-500 to-purple-500',
    projectPath: 'basic/projects/microservices',
    phase: 3,
    phaseName: 'Distributed & Cloud',
    order: 1,
    topics: ['Service discovery', 'API gateway', 'Circuit breaker', 'Distributed tracing', 'Service mesh'],
    learningOutcomes: [
      'Design microservices with clear boundaries',
      'Implement service registration and discovery',
      'Build API gateway for routing and aggregation',
      'Add resilience patterns like circuit breakers',
    ],
    prerequisites: ['gRPC services', 'REST API design', 'Docker basics'],
    exercises: [
      {
        id: 'micro-1',
        title: 'Service Registration',
        description: 'Implement service registry',
        requirements: ['Register services on startup', 'Heartbeat mechanism', 'Deregister on shutdown'],
        difficulty: 'medium',
        starterCode: 'basic/projects/microservices/exercises/01-registry/main.go',
        solutionHint: 'Use in-memory registry with TTL-based cleanup',
        completionMethod: 'test',
      },
      {
        id: 'micro-2',
        title: 'API Gateway',
        description: 'Build a reverse proxy for microservices',
        requirements: ['Route requests based on path', 'Aggregate multiple service responses', 'Handle service unavailable'],
        difficulty: 'hard',
        starterCode: 'basic/projects/microservices/exercises/02-gateway/main.go',
        solutionHint: 'Use httputil.ReverseProxy with custom director',
        completionMethod: 'test',
      },
      {
        id: 'micro-3',
        title: 'Circuit Breaker',
        description: 'Implement fault tolerance pattern',
        requirements: ['Track failure count', 'Open circuit after threshold', 'Attempt recovery periodically'],
        difficulty: 'hard',
        starterCode: 'basic/projects/microservices/exercises/03-breaker/main.go',
        solutionHint: 'Use state machine: closed -> open -> half-open',
        completionMethod: 'manual',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/microservices',
  },
  {
    id: 'docker-kubernetes',
    title: 'Docker & Kubernetes',
    description: 'Containerize Go applications and deploy to Kubernetes with proper configuration.',
    duration: '5-7 hours',
    difficulty: 'intermediate',
    icon: '🐳',
    color: 'bg-gradient-to-r from-blue-600 to-cyan-600',
    projectPath: 'basic/projects/docker-kubernetes',
    phase: 3,
    phaseName: 'Distributed & Cloud',
    order: 2,
    topics: ['Dockerfile', 'Docker Compose', 'Kubernetes manifests', 'Helm charts', 'Deployment strategies'],
    learningOutcomes: [
      'Write efficient Dockerfiles for Go applications',
      'Define multi-container applications with Docker Compose',
      'Create Kubernetes deployments and services',
      'Implement rolling updates and rollbacks',
    ],
    prerequisites: ['Go basics', 'Docker basics', 'Command line proficiency'],
    exercises: [
      {
        id: 'dk-1',
        title: 'Multi-stage Dockerfile',
        description: 'Optimize Go application for minimal image size',
        requirements: ['Use multi-stage build', 'Minimize final image size', 'Handle non-root user'],
        difficulty: 'easy',
        starterCode: 'basic/projects/docker-kubernetes/exercises/01-dockerfile/main.go',
        solutionHint: 'Build in golang container, copy binary to alpine',
        completionMethod: 'manual',
      },
      {
        id: 'dk-2',
        title: 'Docker Compose',
        description: 'Define multi-container environment',
        requirements: ['Go service + PostgreSQL + Redis', 'Health checks', 'Volume mounts for data'],
        difficulty: 'medium',
        starterCode: 'basic/projects/docker-kubernetes/exercises/02-compose/main.go',
        solutionHint: 'Use official images, link with networks',
        completionMethod: 'manual',
      },
      {
        id: 'dk-3',
        title: 'Kubernetes Deployment',
        description: 'Deploy Go service to Kubernetes',
        requirements: ['Deployment with replicas', 'Service for internal access', 'ConfigMap for configuration'],
        difficulty: 'medium',
        starterCode: 'basic/projects/docker-kubernetes/exercises/03-k8s/main.go',
        solutionHint: 'Use kubectl apply -f with YAML manifests',
        completionMethod: 'manual',
      },
      {
        id: 'dk-4',
        title: 'Rolling Update',
        description: 'Implement zero-downtime deployment',
        requirements: ['Configure rolling update strategy', 'Monitor rollout progress', 'Rollback on failure'],
        difficulty: 'hard',
        starterCode: 'basic/projects/docker-kubernetes/exercises/04-rolling/main.go',
        solutionHint: 'Set maxSurge and maxUnavailable, use kubectl rollout',
        completionMethod: 'manual',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/docker-kubernetes',
  },
  {
    id: 'distributed-systems',
    title: 'Distributed Systems Patterns',
    description: 'Implement consensus algorithms, leader election, and distributed coordination.',
    duration: '6-8 hours',
    difficulty: 'advanced',
    icon: '🌐',
    color: 'bg-gradient-to-r from-slate-600 to-zinc-600',
    projectPath: 'basic/projects/distributed-systems',
    phase: 3,
    phaseName: 'Distributed & Cloud',
    order: 3,
    topics: ['Raft consensus', 'Leader election', 'Two-phase commit', 'Sharding', 'Replication'],
    learningOutcomes: [
      'Understand Raft consensus algorithm',
      'Implement leader election in distributed system',
      'Handle network partitions and recovery',
      'Design for eventual consistency',
    ],
    prerequisites: ['Concurrency patterns', 'Microservices architecture'],
    exercises: [
      {
        id: 'dist-1',
        title: 'Leader Election',
        description: 'Implement mutex-based leader election',
        requirements: ['Detect current leader', 'Elect new leader on failure', 'Handle concurrent elections'],
        difficulty: 'hard',
        starterCode: 'basic/projects/distributed-systems/exercises/01-election/main.go',
        solutionHint: 'Use compare-and-swap for atomic leader selection',
        completionMethod: 'manual',
      },
      {
        id: 'dist-2',
        title: 'Heartbeat Protocol',
        description: 'Monitor node health with heartbeats',
        requirements: ['Send periodic heartbeats', 'Detect failed nodes', 'Timeout-based failure detection'],
        difficulty: 'medium',
        starterCode: 'basic/projects/distributed-systems/exercises/02-heartbeat/main.go',
        solutionHint: 'Use channels with select and timeout',
        completionMethod: 'test',
      },
      {
        id: 'dist-3',
        title: 'Log Replication',
        description: 'Replicate log entries across nodes',
        requirements: ['Append-only log structure', 'Replicate to majority', 'Commit entries after replication'],
        difficulty: 'hard',
        starterCode: 'basic/projects/distributed-systems/exercises/03-replication/main.go',
        solutionHint: 'Use term and index for ordering, majority quorums for commit',
        completionMethod: 'manual',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/distributed-systems',
  },

  // Phase 4: Specialized Domains (4 topics)
  {
    id: 'data-processing',
    title: 'Data Processing & Pipelines',
    description: 'Build ETL pipelines, stream processing, and data transformation systems.',
    duration: '5-7 hours',
    difficulty: 'intermediate',
    icon: '⚙️',
    color: 'bg-gradient-to-r from-orange-500 to-amber-500',
    projectPath: 'basic/projects/data-processing',
    phase: 4,
    phaseName: 'Specialized Domains',
    order: 1,
    topics: ['ETL pipelines', 'Batch processing', 'Stream processing', 'Data transformation'],
    learningOutcomes: [
      'Design extract-transform-load pipelines',
      'Process data in batches efficiently',
      'Handle streaming data with backpressure',
      'Implement data validation and error handling',
    ],
    prerequisites: ['Concurrency patterns', 'I/O operations'],
    exercises: [
      {
        id: 'data-1',
        title: 'CSV ETL Pipeline',
        description: 'Build CSV extraction and transformation',
        requirements: ['Read large CSV files', 'Transform data according to rules', 'Write output to JSON'],
        difficulty: 'easy',
        starterCode: 'basic/projects/data-processing/exercises/01-csv/main.go',
        solutionHint: 'Use encoding/csv with buffered processing',
        completionMethod: 'test',
      },
      {
        id: 'data-2',
        title: 'Streaming Aggregation',
        description: 'Aggregate data in motion',
        requirements: ['Process events in real-time', 'Calculate rolling averages', 'Handle late-arriving data'],
        difficulty: 'medium',
        starterCode: 'basic/projects/data-processing/exercises/02-stream/main.go',
        solutionHint: 'Use time windows and incremental aggregation',
        completionMethod: 'test',
      },
      {
        id: 'data-3',
        title: 'Data Validation',
        description: 'Implement comprehensive data validation',
        requirements: ['Validate field formats', 'Check referential integrity', 'Report validation errors'],
        difficulty: 'medium',
        starterCode: 'basic/projects/data-processing/exercises/03-validation/main.go',
        solutionHint: 'Create validation pipeline with error aggregation',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/data-processing',
  },
  {
    id: 'observability',
    title: 'Observability & Telemetry',
    description: 'Implement logging, metrics, and tracing for production Go applications.',
    duration: '4-6 hours',
    difficulty: 'intermediate',
    icon: '📊',
    color: 'bg-gradient-to-r from-cyan-600 to-sky-600',
    projectPath: 'basic/projects/observability',
    phase: 4,
    phaseName: 'Specialized Domains',
    order: 2,
    topics: ['Structured logging', 'Metrics', 'Distributed tracing', 'Alerting'],
    learningOutcomes: [
      'Implement structured logging with levels',
      'Expose Prometheus metrics endpoints',
      'Add OpenTelemetry tracing',
      'Correlate logs with trace IDs',
    ],
    prerequisites: ['Go basics', 'HTTP handling'],
    exercises: [
      {
        id: 'obs-1',
        title: 'Structured Logging',
        description: 'Implement JSON structured logging',
        requirements: ['Log levels (debug, info, warn, error)', 'JSON output format', 'Context fields'],
        difficulty: 'easy',
        starterCode: 'basic/projects/observability/exercises/01-logging/main.go',
        solutionHint: 'Use zerolog or zap for structured logging',
        completionMethod: 'test',
      },
      {
        id: 'obs-2',
        title: 'Prometheus Metrics',
        description: 'Expose application metrics',
        requirements: ['Define counters, gauges, histograms', 'Expose /metrics endpoint', 'Add labels for filtering'],
        difficulty: 'medium',
        starterCode: 'basic/projects/observability/exercises/02-metrics/main.go',
        solutionHint: 'Use prometheus/client_golang library',
        completionMethod: 'test',
      },
      {
        id: 'obs-3',
        title: 'Distributed Tracing',
        description: 'Add OpenTelemetry tracing',
        requirements: ['Create spans for operations', 'Propagate trace context', 'Export to Jaeger'],
        difficulty: 'medium',
        starterCode: 'basic/projects/observability/exercises/03-tracing/main.go',
        solutionHint: 'Use otel/sdk and otel/exporters for tracing',
        completionMethod: 'manual',
      },
      {
        id: 'obs-4',
        title: 'Health Checks',
        description: 'Implement comprehensive health endpoints',
        requirements: ['Liveness probe', 'Readiness probe', 'Detailed status with component health'],
        difficulty: 'easy',
        starterCode: 'basic/projects/observability/exercises/04-health/main.go',
        solutionHint: 'Separate /health/live and /health/ready endpoints',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/observability',
  },
  {
    id: 'security',
    title: 'Security & Cryptography',
    description: 'Implement secure authentication, encryption, and security best practices.',
    duration: '5-6 hours',
    difficulty: 'advanced',
    icon: '🔒',
    color: 'bg-gradient-to-r from-gray-600 to-slate-700',
    projectPath: 'basic/projects/security',
    phase: 4,
    phaseName: 'Specialized Domains',
    order: 3,
    topics: ['Password hashing', 'JWT tokens', 'Encryption', 'Security headers'],
    learningOutcomes: [
      'Hash passwords securely with bcrypt/argon2',
      'Sign and verify JWT tokens',
      'Implement symmetric and asymmetric encryption',
      'Add security headers to HTTP responses',
    ],
    prerequisites: ['REST API design', 'HTTP handling'],
    exercises: [
      {
        id: 'sec-1',
        title: 'Password Hashing',
        description: 'Implement secure password storage',
        requirements: ['Hash passwords with bcrypt', 'Verify passwords correctly', 'Handle hashing cost settings'],
        difficulty: 'easy',
        starterCode: 'basic/projects/security/exercises/01-password/main.go',
        solutionHint: 'Use golang.org/x/crypto/bcrypt',
        completionMethod: 'test',
      },
      {
        id: 'sec-2',
        title: 'JWT Authentication',
        description: 'Implement JWT token handling',
        requirements: ['Sign tokens with secret', 'Verify and parse tokens', 'Handle token expiration'],
        difficulty: 'medium',
        starterCode: 'basic/projects/security/exercises/02-jwt/main.go',
        solutionHint: 'Use golang-jwt/jwt v5 for token operations',
        completionMethod: 'test',
      },
      {
        id: 'sec-3',
        title: 'AES Encryption',
        description: 'Implement symmetric encryption',
        requirements: ['Encrypt data with AES-GCM', 'Decrypt data correctly', 'Handle nonce correctly'],
        difficulty: 'medium',
        starterCode: 'basic/projects/security/exercises/03-aes/main.go',
        solutionHint: 'Use crypto/aes and crypto/cipher packages',
        completionMethod: 'test',
      },
      {
        id: 'sec-4',
        title: 'Security Headers',
        description: 'Add security headers to HTTP responses',
        requirements: ['Set CSP header', 'Add HSTS header', 'Implement rate limiting'],
        difficulty: 'medium',
        starterCode: 'basic/projects/security/exercises/04-headers/main.go',
        solutionHint: 'Create middleware that sets headers on all responses',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/security',
  },
  {
    id: 'testing-best-practices',
    title: 'Testing & Testability',
    description: 'Master unit testing, integration testing, and mocking in Go.',
    duration: '4-5 hours',
    difficulty: 'intermediate',
    icon: '🧪',
    color: 'bg-gradient-to-r from-rose-500 to-pink-500',
    projectPath: 'basic/projects/testing-best-practices',
    phase: 4,
    phaseName: 'Specialized Domains',
    order: 4,
    topics: ['Unit testing', 'Mocking', 'Test fixtures', 'Benchmarking', 'Coverage'],
    learningOutcomes: [
      'Write effective unit tests with table-driven tests',
      'Use interfaces for testability',
      'Mock dependencies with interfaces',
      'Write benchmarks and measure performance',
    ],
    prerequisites: ['Go basics'],
    exercises: [
      {
        id: 'test-1',
        title: 'Table-Driven Tests',
        description: 'Write parameterized tests',
        requirements: ['Use table-driven test pattern', 'Test multiple cases in one function', 'Provide descriptive test names'],
        difficulty: 'easy',
        starterCode: 'basic/projects/testing-best-practices/exercises/01-table/main.go',
        solutionHint: 'Slice of test cases with input, expected output',
        completionMethod: 'test',
      },
      {
        id: 'test-2',
        title: 'Mocking Interfaces',
        description: 'Test with mocked dependencies',
        requirements: ['Define interfaces for dependencies', 'Create mock implementations', 'Verify mock interactions'],
        difficulty: 'medium',
        starterCode: 'basic/projects/testing-best-practices/exercises/02-mocks/main.go',
        solutionHint: 'Use counterfeiter or manual mocks',
        completionMethod: 'test',
      },
      {
        id: 'test-3',
        title: 'HTTP Handler Testing',
        description: 'Test HTTP handlers in isolation',
        requirements: ['Use httptest.NewRequest', 'Test status codes', 'Test response bodies'],
        difficulty: 'medium',
        starterCode: 'basic/projects/testing-best-practices/exercises/03-handlers/main.go',
        solutionHint: 'Use httptest package for request/response',
        completionMethod: 'test',
      },
      {
        id: 'test-4',
        title: 'Benchmarking',
        description: 'Write and run benchmarks',
        requirements: ['Create BenchmarkX functions', 'Use testing.B properly', 'Compare implementation performance'],
        difficulty: 'medium',
        starterCode: 'basic/projects/testing-best-practices/exercises/04-bench/main.go',
        solutionHint: 'Use b.ReportAllocs() and testing.B.N loop',
        completionMethod: 'manual',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/testing-best-practices',
  },

  // Phase 5: GraphQL & Integration (1 topic)
  {
    id: 'graphql-api',
    title: 'GraphQL API',
    description: 'Build flexible GraphQL APIs with queries, mutations, subscriptions, and schema stitching.',
    duration: '5-7 hours',
    difficulty: 'intermediate',
    icon: '🔀',
    color: 'bg-gradient-to-r from-pink-500 to-rose-500',
    projectPath: 'basic/projects/graphql-api',
    phase: 5,
    phaseName: 'GraphQL & Integration',
    order: 1,
    topics: ['Schema definition', 'Resolvers', 'Mutations', 'Subscriptions', 'Schema stitching'],
    learningOutcomes: [
      'Design GraphQL schemas with SDL',
      'Implement resolvers for queries and mutations',
      'Handle GraphQL subscriptions with WebSocket',
      'Validate inputs and handle errors',
    ],
    prerequisites: ['REST API design', 'WebSocket'],
    exercises: [
      {
        id: 'gql-1',
        title: 'Basic GraphQL Server',
        description: 'Set up GraphQL server with schema',
        requirements: ['Define schema with types and fields', 'Implement query resolver', 'Handle null values'],
        difficulty: 'medium',
        starterCode: 'basic/projects/graphql-api/exercises/01-schema/main.go',
        solutionHint: 'Use gqlgen or graphql-go library',
        completionMethod: 'test',
      },
      {
        id: 'gql-2',
        title: 'Mutations',
        description: 'Implement GraphQL mutations',
        requirements: ['Define mutation schema', 'Implement mutation resolvers', 'Validate input arguments'],
        difficulty: 'medium',
        starterCode: 'basic/projects/graphql-api/exercises/02-mutations/main.go',
        solutionHint: 'Return the created/updated object from mutations',
        completionMethod: 'test',
      },
      {
        id: 'gql-3',
        title: 'Subscriptions',
        description: 'Implement real-time subscriptions',
        requirements: ['Define subscription schema', 'Use pub/sub for updates', 'Handle subscription lifecycle'],
        difficulty: 'hard',
        starterCode: 'basic/projects/graphql-api/exercises/03-subscriptions/main.go',
        solutionHint: 'Use WebSocket-based subscription transport',
        completionMethod: 'manual',
      },
      {
        id: 'gql-4',
        title: 'Error Handling',
        description: 'Handle GraphQL errors properly',
        requirements: ['Return typed errors', 'Handle validation errors', 'Propagate errors from resolvers'],
        difficulty: 'medium',
        starterCode: 'basic/projects/graphql-api/exercises/04-errors/main.go',
        solutionHint: 'Use graphql.Errorf and errors.Is in resolvers',
        completionMethod: 'test',
      },
    ],
    githubUrl: 'https://github.com/DimaJoyti/go-pro/tree/main/basic/projects/graphql-api',
  },
];

// Helper functions

/**
 * Get all topics grouped by phase number
 */
export function getTopicsByPhase(): Record<number, Topic[]> {
  return topics.reduce((acc, topic) => {
    if (!acc[topic.phase]) acc[topic.phase] = [];
    acc[topic.phase].push(topic);
    return acc;
  }, {} as Record<number, Topic[]>);
}

/**
 * Get a single topic by its ID (slug)
 */
export function getTopicById(id: string): Topic | undefined {
  return topics.find(t => t.id === id);
}

/**
 * Get topics for a specific phase
 */
export function getTopicsByPhaseNumber(phase: number): Topic[] {
  return topics.filter(t => t.phase === phase).sort((a, b) => a.order - b.order);
}

/**
 * Get phase metadata for a specific phase
 */
export function getPhaseMetadata(phase: number) {
  return phaseMetadata.find(p => p.phase === phase);
}

/**
 * Get total exercise count across all topics
 */
export function getTotalExerciseCount(): number {
  return topics.reduce((sum, topic) => sum + topic.exercises.length, 0);
}
